# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@master


    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
#      with:
#          node-version: 16
#          registry-url: https://npm.pkg.github.com/
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        TARGET_REPO: 864588080jim/vue3_study
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn doc:build
        BUILD_DIR: blog/.vuepress/dist/
